### ISSUE TITLE
Add remaining admin APIs

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/healthchecks-rs#1]
As noted in the healthchecks [README](https://github.com/msfjarvis/healthchecks-rs/blob/develop/healthchecks/README.md), there are a couple remaining admin APIs that should be relatively straightforward to add.

Resources:

- [API docs](https://healthchecks.io/docs/api)
- [Transform tools](https://transform.tools/json-to-rust-serde) (to convert JSON to a serde compatible struct)﻿

**Comment by nidble** [comment]
Can I work on this? Thanks!

**Comment by msfjarvis** [comment]
> Can I work on this? Thanks!

Absolutely, have at it!
