### ISSUE TITLE
Restore retry mechanism from healthchecks v1

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/healthchecks-rs#17]
The healthchecks library upgraded to [`ureq`](https://github.com/algesten/ureq) 2.0 as part of the healthchecks 2.0 release, missing a crucial feature: retries. The pings module [still contains](https://github.com/msfjarvis/healthchecks-rs/blob/c0365eb5afcb50f58c34757f35d45eff06c2fe21/healthchecks/src/ping.rs#L75-L81) remnants of that code. Bringing it back is a nice to have option for resilience.

**Comment by SanchithHegde** [comment]
I'd like to give this a try.
